name: Build and Release on Tag

on:
  push: 
    branches: [main]

#    tags:
#      - 'v*'
#      - 'Ver*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: __tool/release.sh

      - name: Delete Release
        run: gh release delete ${{github.ref_name}}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Create Release
        run: gh release create ${{github.ref_name}} *.tar.bz2 *.zip
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}



