name: Build and Release on Tag

on:
  push:
    tags:
      - 'v*'
      - 'Ver*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Archive Production Build
      - run: __tool/release.sh

      - name: Create Release
        run: gh release create ${{github.ref_name}}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}



